name: simpleConsole
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Ganesan, Michael (LRC) <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: ^1.4.1
  colorize: ^2.0.0
  ansicolor: ^1.0.2


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
